apiVersion: rbac.authorization.k8s.io/v1  #miniO access role
kind: Role
metadata:
  name: minio-access
  namespace: app
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["minio-secret"]
  verbs: ["get"]
---
# RoleBinding for data-service only
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: data-service-minio-access
  namespace: app
subjects:
- kind: ServiceAccount
  name: data-service-sa
  namespace: app
roleRef:
  kind: Role
  name: minio-access
  apiGroup: rbac.authorization.k8s.io